### ISSUE TITLE
Device byte endianness is ignored

### ISSUE THREAD

**Issue by pwoo** [adriangibbons/php-fit-file-analysis#11] opened 2015-08-13 07:53 UTC
Hi Adrian,

Thanks for the recent fix. In addition to that issue, there is another problem I've been encountering with a specific FIT file. Unfortunately, I am still quite unfamiliar with the FIT spec and cannot pinpoint what the problem is during parsing. What I can tell you is that it gives the error:

```
Undefined index: record
```

And that it works in GoldenCheetah. I have uploaded the file to https://www.mediafire.com/?hgc99xr1oc5ic98

Thanks.

**Comment by adriangibbons** [comment] 2015-08-13 08:11
Hey @pwoo, no worries!

I will take a look at your file later. Can you provide some context? E.g.
- What device was used to record it?
- What kind of activity is it? Cycling/running/etc
- What sensors were connected? HR, power, cadence/speed, foot pod etc. 

Cheers

**Comment by adriangibbons** [comment] 2015-08-13 13:52
I loaded your file up and outputted the debug information:

``` php
<?php $pFFA->show_debug_info(); ?>
```

![pwoo-fitdefnmesgs](https://cloud.githubusercontent.com/assets/10218647/9251237/c5309fb0-4204-11e5-9b6e-6c1ddfcdc7b7.png)

So the file doesn't appear to contain any valid messages as there isn't a mesg_num of 5120 in the FIT standard. However, we know it is not a corrupted file as it works with Golden Cheetah and I recognise the field definitions:

> 0 position_lat
> 1 position_long
> 2 altitude
> 3 heart_rate
> 4 cadence
> 5 distance
> 7 power
> 253   timestamp

So clearly something isn't working right as the mesg_num should be 20 for record data...

**Comment by adriangibbons** [comment] 2015-08-13 13:57
So the issue is that the **product architecture** for this file is Big Endian and the class as it stands assumes everything is Little Endian or machine byte order. Line 680 of the class skips over the architecture byte.
_Table 4-3. Definition Message Contents of the file 'D00001275 Flexible & Interoperable Data Transfer (FIT) Protocol Rev 1.7.pdf' in the FIT SDK._

Sure enough if I replace:

``` php
$this->file_pointer++;  // Architecture - IGNORED
```

with

``` php
$architecture = ord(substr($this->file_contents, $this->file_pointer, 1));  // Architecture
var_dump($architecture);
die();
```

I get `int 1` (Big Endian) for your file and `int 0` (Little Endian) for any others of mine that I try. Interested to know whether this file came from a Garmin (which model?) or if it was exported from a website as I had not seen a Big Endian architecture file so far...

I have an idea of how to resolve this, but it will have to wait until the weekend!

**Comment by adriangibbons** [comment] 2015-08-13 14:02
You can see that I am currently only considering the Little Endian [PHP pack() format characters](http://php.net/manual/en/function.pack.php) C,c,S,v,l,V,f,d:

``` php
private $types = array(
    0   => 'Ctmp',  // enum
    1   => 'ctmp',  // sint8
    2   => 'Ctmp',  // uint8
    131 => 'Stmp',  // sint16
    132 => 'vtmp',  // uint16
    133 => 'ltmp',  // sint32
    134 => 'Vtmp',  // uint32
    7   => 'Ctmp',  // string
    136 => 'ftmp',  // float32
    137 => 'dtmp',  // float64
    10  => 'Ctmp',  // uint8z
    139 => 'vtmp',  // uint16z
    140 => 'Vtmp',  // uint32z
    13  => 'Ctmp',  // byte
);
```

**Comment by adriangibbons** [comment] 2015-08-13 14:08
The record data field definitions from your file:

> position_lat (0)
> 133 = sint32 = l = signed long (always 32 bit, machine byte order)
> 
> position_long (1)
> 133 = sint32 = l
> 
> altitude (2)
> 132 = uint16 = v = unsigned short (always 16 bit, little endian byte order)
> 
> heart_rate (3)
> 2 = uint8 = C = unsigned char
> 
> cadence (4)
> 2 =uint8 = C
> 
> distance (5)
> 134 = uint32 = V = unsigned long (always 32 bit, little endian byte order)
> 
> power (7)
> 132 = uint16 = v
> 
> timestamp (253)
> 134 = uint32 = V

v has a Big Endian counterpart, n
V has a Big Endian counterpart, N
**l is always machine byte order, will have to have a think about this!**

**Comment by pwoo** [comment] 2015-08-13 14:46
The file is being exported via a mobile app still in development (not by me). I have been told that they are using PowerTap Power Meter for power, torque and speed, GSC10 for cadence and GPolar H7 for heart rate.

**Comment by adriangibbons** [comment] 2015-08-14 14:06
Thanks @pwoo - I suspected that the file had not been created with a Garmin due to it being Big Endian and the FIT Definition Messages it contains (or doesn't)!

If you want to try [php-FIT-File-Analysis.php from the endianness branch](https://github.com/adriangibbons/php-FIT-File-Analysis/blob/endianness/php-FIT-File-Analysis.php), I have added some changes today to make your FIT file work with my class. The changes just need some more testing and thought before I merge the commits into the master branch and close this issue.

![staticmap](https://cloud.githubusercontent.com/assets/10218647/9275538/4cb3a8ee-42d0-11e5-869d-9045bcc9d152.png)

**Comment by adriangibbons** [comment] 2015-08-15 03:53
Enhanced the `fix_data()` function to cater for all fields captured that were stored as unsigned ints that need to be converted to being signed as `unpack()` doesn't allow you to specify endianness for signed ints.

Merged into the master branch too (#13) as seems to be working fine. Let me know if all good and I wIll close the issue and delete the endianness branch.

**Closed as completed** 2015-08-16 01:14 UTC
Labels: bug

**Comment by pwoo** [comment] 2015-08-17 16:58
Thanks. It's no longer crashing for this file.

However, it looks like file_id doesn't exist in data_mesgs (getting undefined index). If I'm intepreting the debug output correctly (image attached), it should be there?

![capture](https://cloud.githubusercontent.com/assets/799069/9310729/889ac7a0-44df-11e5-8f8c-8b2392d2fdcf.PNG)

**Comment by pwoo** [comment] 2015-08-17 18:23
@adriangibbons, 

In addition to the above, I've attempted using a stripped down version of pFFA-Basic-Test.php to simply instantiate phpFITFileAnalysis (and nothing else):

FIT2015_8_8_ 5_41_44.fit
Time: 1.03 minutes, Memory: 40.75Mb

It's taking unexpectedly long to parse compared to typical files.

**Comment by adriangibbons** [comment] 2015-08-18 12:15
Hi @pwoo, I'll answer your two questions separately:

> However, it looks like file_id doesn't exist in data_mesgs (getting undefined index). If I'm interpreting the debug output correctly (image attached), it should be there?

It's a reasonable assumption that there _should_ be corresponding **data** messages for a give **definition** message, otherwise why bother defining it? However, I don't see anything that would prevent someone from creating a parseable FIT file that does not have data messages for a given definition message.

I'm confident that the **file_id** information is not contained in the file you have shared:
- I performed some (reasonably quick) debugging of the file and could not see this information being dropped by the phpFITFileAnalysis class.
- I used the _FitToCSV.bat_ program from within the Java folder of the FIT SDK to convert it to a [CSV file](https://dl.dropboxusercontent.com/u/21386/FIT2015_8_8_%205_41_44.csv) and there's no file_id data message, only a definition.
- I also just uploaded the file to Strava and noticed that the manufacturer and product information (e.g. Garmin 500) is not included for the activity. I've deleted the activity as I don't want it included in my totals, but some very nice wattage there I see ;)

Cheers, Adrian.

**Comment by adriangibbons** [comment] 2015-08-18 12:42
> It's taking unexpectedly long to parse compared to typical files.

Yes, I am experiencing the same - but only with this particular file.

I think the FIT file is suspect here (but I may be wrong!). You mentioned that it was created by a mobile app being developed by someone else - how confident is the developer that the FIT files are being created optimally?

For example, the record definition messages are defined over and over again, often with just two fields e.g. one of heart rate, distance, power; and a timestamp. This is not very efficient and may be the cause of the performance degradation. Something more compact, such as the below may help, but dependent on the developer:

![record_data_defn](https://cloud.githubusercontent.com/assets/10218647/9329915/29391fdc-45e8-11e5-8e37-1e9d8f766066.png)

Also, I'd consider that without the `file_id` data message that it is not a valid FIT file as **Figure 9-1. Activity File** from _'FIT File Types Description, Rev 1.7'_ suggests you need to have the definition and data messages. I note that other common/useful FIT fields are not included such as lap and session data.

Seems that the hold-up is in `phpFITFileAnalyser::read_data_records()` - but I don't have a good explanation without more investigation and I'm probably not going to do so unless I see a similar problem in FIT files created by other devices.

Hope the above helps explain what is going on and is perhaps useful to the developer of the mobile app!

Cheers, Adrian.

**Comment by pwoo** [comment] 2015-08-18 19:35
Thanks a lot Adrian, I've forwarded the analysis to the interested parties.

**Comment by adriangibbons** [comment] 2015-08-19 07:10
Great stuff - the manufacturer and garmin_product fields in the file_id message are enumerated types:

![image](https://cloud.githubusercontent.com/assets/10218647/9350378/f16bc078-4682-11e5-9bce-443ba7ba3b81.png)

![image](https://cloud.githubusercontent.com/assets/10218647/9350380/0125984a-4683-11e5-9299-539eb270e56e.png)

So the developer would need to request to be added to the FIT profile (if they're not already) so that they can populate this message with the value that relates to them as the manufacturer. It seems product is only relevant for Garmin devices but I may be wrong.

Cheers
